-- Enhanced Hotel Configuration
ALTER TABLE config_hotel 
ADD COLUMN logo VARCHAR(255) AFTER nit,
ADD COLUMN timezone VARCHAR(50) DEFAULT 'America/Bogota' AFTER logo,
ADD COLUMN moneda VARCHAR(3) DEFAULT 'COP' AFTER timezone,
ADD COLUMN checkin_time TIME DEFAULT '15:00:00' AFTER moneda,
ADD COLUMN checkout_time TIME DEFAULT '12:00:00' AFTER checkin_time,
ADD COLUMN politica_cancelacion TEXT AFTER checkout_time,
ADD COLUMN descripcion TEXT AFTER politica_cancelacion,
ADD COLUMN website VARCHAR(255) AFTER descripcion,
ADD COLUMN email_reservas VARCHAR(100) AFTER website,
ADD COLUMN telefono_reservas VARCHAR(20) AFTER email_reservas,
ADD COLUMN capacidad_maxima INT DEFAULT 100 AFTER telefono_reservas,
ADD COLUMN categoria_hotel VARCHAR(50) DEFAULT '3 estrellas' AFTER capacidad_maxima,
ADD COLUMN amenities JSON AFTER categoria_hotel,
ADD COLUMN servicios JSON AFTER amenities,
ADD COLUMN idiomas JSON AFTER servicios,
ADD COLUMN checkin_early_time TIME DEFAULT '12:00:00' AFTER idiomas,
ADD COLUMN checkout_late_time TIME DEFAULT '14:00:00' AFTER checkin_early_time,
ADD COLUMN impuesto_turismo DECIMAL(5,2) DEFAULT 0.00 AFTER checkout_late_time,
ADD COLUMN impuesto_iva DECIMAL(5,2) DEFAULT 19.00 AFTER impuesto_turismo,
ADD COLUMN politica_mascotas ENUM('permitidas', 'no_permitidas', 'con_cargo') DEFAULT 'no_permitidas' AFTER impuesto_iva,
ADD COLUMN cargo_mascotas DECIMAL(10,2) DEFAULT 0.00 AFTER politica_mascotas,
ADD COLUMN politica_ninos ENUM('gratis', 'con_cargo', 'no_permitidos') DEFAULT 'gratis' AFTER cargo_mascotas,
ADD COLUMN cargo_ninos DECIMAL(10,2) DEFAULT 0.00 AFTER politica_ninos,
ADD COLUMN wifi_incluido TINYINT(1) DEFAULT 1 AFTER cargo_ninos,
ADD COLUMN desayuno_incluido TINYINT(1) DEFAULT 0 AFTER wifi_incluido,
ADD COLUMN parking_incluido TINYINT(1) DEFAULT 0 AFTER desayuno_incluido,
ADD COLUMN gym_incluido TINYINT(1) DEFAULT 0 AFTER parking_incluido,
ADD COLUMN piscina_incluido TINYINT(1) DEFAULT 0 AFTER gym_incluido,
ADD COLUMN spa_incluido TINYINT(1) DEFAULT 0 AFTER piscina_incluido;

-- Update existing record with default values
UPDATE config_hotel SET 
    timezone = 'America/Bogota',
    moneda = 'COP',
    checkin_time = '15:00:00',
    checkout_time = '12:00:00',
    checkin_early_time = '12:00:00',
    checkout_late_time = '14:00:00',
    impuesto_turismo = 0.00,
    impuesto_iva = 19.00,
    wifi_incluido = 1,
    desayuno_incluido = 0,
    parking_incluido = 0,
    gym_incluido = 0,
    piscina_incluido = 0,
    spa_incluido = 0,
    categoria_hotel = '3 estrellas',
    capacidad_maxima = 100,
    amenities = JSON_OBJECT('aire_acondicionado', true, 'tv', true, 'minibar', true, 'caja_fuerte', true, 'secador', true),
    servicios = JSON_OBJECT('recepcion_24h', true, 'conserje', false, 'lavanderia', true, 'room_service', false, 'spa', false),
    idiomas = JSON_ARRAY('español', 'inglés'),
    politica_cancelacion = 'Cancelación gratuita hasta 48 horas antes del check-in. Después de ese tiempo, se cobrará el 50% del total de la reserva.',
    descripcion = 'Hotel Tame ofrece comodidad y calidad en el corazón de la ciudad. Perfecto para viajeros de negocios y turismo.',
    website = 'https://www.hoteltame.com',
    email_reservas = 'reservas@hoteltame.com',
    telefono_reservas = '+57 1 2345678';

-- Hotel Settings Table (for additional configuration)
CREATE TABLE IF NOT EXISTS hotel_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hotel_id INT DEFAULT 1,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT,
    setting_type ENUM('string', 'number', 'boolean', 'json') DEFAULT 'string',
    category VARCHAR(50),
    descripcion TEXT,
    editable TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (hotel_id) REFERENCES config_hotel(id) ON DELETE RESTRICT,
    UNIQUE KEY unique_setting (hotel_id, setting_key),
    INDEX idx_category (category),
    INDEX idx_hotel_id (hotel_id),
    INDEX idx_deleted_at (deleted_at)
);

-- Insert default hotel settings
INSERT INTO hotel_settings (setting_key, setting_value, setting_type, category, descripcion) VALUES
('max_guests_per_room', 4, 'number', 'capacidad', 'Máximo de huéspedes permitidos por habitación'),
('min_checkin_age', 18, 'number', 'politicas', 'Edad mínima para check-in sin acompañante'),
('pet_fee_per_night', 50000, 'number', 'politicas', 'Cargo por mascota por noche'),
('early_checkin_fee', 50000, 'number', 'politicas', 'Cargo por check-in temprano'),
('late_checkout_fee', 50000, 'number', 'politicas', 'Cargo por check-out tardío'),
('no_show_penalty', 100, 'number', 'politicas', 'Porcentaje de penalización por no-show'),
('deposit_required', 1, 'boolean', 'politicas', 'Requiere depósito'),
('deposit_amount', 100000, 'number', 'politicas', 'Monto del depósito'),
('breakfast_price', 25000, 'number', 'servicios', 'Precio del desayuno'),
('parking_price_per_day', 20000, 'number', 'servicios', 'Precio del estacionamiento por día'),
('laundry_price_per_kg', 15000, 'number', 'servicios', 'Precio de lavandería por kilo'),
('room_service_hours', '06:00-23:00', 'string', 'servicios', 'Horario de room service'),
('spa_hours', '09:00-21:00', 'string', 'servicios', 'Horario del spa'),
('gym_hours', '05:00-23:00', 'string', 'servicios', 'Horario del gimnasio'),
('pool_hours', '07:00-22:00', 'string', 'servicios', 'Horario de la piscina'),
('reception_hours', '00:00-24:00', 'string', 'servicios', 'Horario de recepción'),
('currency_symbol', '$', 'string', 'general', 'Símbolo de moneda'),
('date_format', 'Y-m-d', 'string', 'general', 'Formato de fecha'),
('time_format', 'H:i', 'string', 'general', 'Formato de hora'),
('decimal_separator', ',', 'string', 'general', 'Separador decimal'),
('thousands_separator', '.', 'string', 'general', 'Separador de miles'),
('default_language', 'es', 'string', 'general', 'Idioma por defecto'),
('timezone_offset', '-5', 'number', 'general', 'Offset de zona horaria'),
('enable_online_booking', 1, 'boolean', 'reservas', 'Habilitar reservas online'),
('enable_payment_online', 1, 'boolean', 'pagos', 'Habilitar pagos online'),
('payment_methods', '["credit_card", "debit_card", "cash", "transfer"]', 'json', 'pagos', 'Métodos de pago aceptados'),
('invoice_prefix', 'FAC-', 'string', 'facturacion', 'Prefijo de facturas'),
('invoice_next_number', 1, 'number', 'facturacion', 'Siguiente número de factura'),
('tax_id_required', 1, 'boolean', 'facturacion', 'Requerir ID fiscal'),
('auto_send_confirmation', 1, 'boolean', 'notificaciones', 'Enviar confirmación automática'),
('auto_send_reminder', 1, 'boolean', 'notificaciones', 'Enviar recordatorios automáticos'),
('reminder_days_before', 2, 'number', 'notificaciones', 'Días antes para enviar recordatorio'),
('enable_reviews', 1, 'boolean', 'reviews', 'Habilitar reseñas'),
('auto_approve_reviews', 0, 'boolean', 'reviews', 'Aprobar reseñas automáticamente'),
('min_stay_for_review', 1, 'number', 'reviews', 'Estancia mínima para dejar reseña'),
('enable_loyalty_program', 1, 'boolean', 'lealtad', 'Habilitar programa de lealtad'),
('points_per_currency', 1, 'number', 'lealtad', 'Puntos por unidad de moneda'),
('points_expiration_days', 365, 'number', 'lealtad', 'Días para expiración de puntos');

-- Hotel Facilities Table
CREATE TABLE IF NOT EXISTS hotel_facilities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hotel_id INT DEFAULT 1,
    nombre VARCHAR(100) NOT NULL,
    tipo ENUM('habitacion', 'general', 'servicio', 'entretenimiento', 'negocios', 'bienestar') NOT NULL,
    descripcion TEXT,
    icono VARCHAR(50),
    disponible TINYINT(1) DEFAULT 1,
    costo_adicional DECIMAL(10,2) DEFAULT 0.00,
    horario VARCHAR(100),
    ubicacion VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (hotel_id) REFERENCES config_hotel(id) ON DELETE RESTRICT,
    INDEX idx_tipo (tipo),
    INDEX idx_disponible (disponible),
    INDEX idx_hotel_id (hotel_id),
    INDEX idx_deleted_at (deleted_at)
);

-- Insert default facilities
INSERT INTO hotel_facilities (nombre, tipo, descripcion, icono, horario) VALUES
('Aire Acondicionado', 'habitacion', 'Aire acondicionado en todas las habitaciones', 'snowflake', '24 horas'),
('WiFi Gratuito', 'general', 'Internet inalámbrico de alta velocidad', 'wifi', '24 horas'),
('Televisión', 'habitacion', 'TV con cable y canales internacionales', 'tv', '24 horas'),
('Minibar', 'habitacion', 'Minibar con bebidas y snacks', 'package', '24 horas'),
('Caja Fuerte', 'habitacion', 'Caja de seguridad electrónica', 'lock', '24 horas'),
('Secador de Pelo', 'habitacion', 'Secador de pelo profesional', 'wind', '24 horas'),
('Recepción 24h', 'servicio', 'Recepción abierta 24 horas', 'users', '24 horas'),
('Conserje', 'servicio', 'Servicio de conserjería', 'user-check', '08:00-20:00'),
('Lavandería', 'servicio', 'Servicio de lavandería', 'shirt', '08:00-18:00'),
('Room Service', 'servicio', 'Servicio a la habitación', 'utensils', '06:00-23:00'),
('Gimnasio', 'bienestar', 'Gimnasio equipado', 'dumbbell', '05:00-23:00'),
('Piscina', 'bienestar', 'Piscina climatizada', 'water', '07:00-22:00'),
('Spa', 'bienestar', 'Centro de spa y masajes', 'heart', '09:00-21:00'),
('Sala de Juntas', 'negocios', 'Sala de juntas equipada', 'briefcase', '08:00-18:00'),
('Business Center', 'negocios', 'Centro de negocios con computadoras', 'desktop', '24 horas'),
('Restaurante', 'general', 'Restaurante con cocina internacional', 'utensils', '06:00-23:00'),
('Bar', 'general', 'Bar con bebidas y aperitivos', 'coffee', '17:00-01:00'),
('Estacionamiento', 'general', 'Estacionamiento cubierto y vigilado', 'car', '24 horas'),
('Terraza', 'general', 'Terraza con vistas a la ciudad', 'sun', '06:00-22:00');
